// DRY RUN — propuesta de migración de plantillas_mensaje (Supabase) a las
// variables gramaticales centrales (bot/ai/gramatica.js). NO ejecuta
// ningún UPDATE. Cada fila fue analizada semánticamente a mano (no hay
// reemplazo ciego de "es"/"son"/"está"/"están"): se distingue entre
// palabras que REALMENTE concuerdan con la cantidad de números de la
// respuesta, e idiomas/participios/pronombres invariantes que ya eran
// correctos para cualquier cantidad.
//
// clasificacion:
//   SEGURO             -> se propone contenido nuevo, ya simulado (Fase 3)
//   REQUIERE_REVISION  -> tiene alguna palabra/estructura NO cubierta por
//                         las 9 variables actuales, o dos listas de números
//                         independientes (reservados vs ocupados) que no se
//                         pueden expresar con una sola cantidad. Migrarlas
//                         a ciegas produciría una oración rota o una
//                         concordancia con la lista equivocada.
//   NO_APLICA          -> ya es gramaticalmente correcta para cualquier
//                         cantidad (estructura invariante), es una plantilla
//                         vacía, o no tiene relación real con conteo de
//                         números (p.ej. info_evento).
module.exports = [

// ============================== cantidad_reservas ==============================
// cantidad = resultado.cantidad (escalar directo, sin listas).
{ id:"e2a84eea-504c-4ab5-afae-2adee877dafe", tipo:"cantidad_reservas", nombre:"Natural", habilitada:true,
  antes:"{{cliente}}, tienes {{cantidad}} número(s) reservado(s).",
  propuesto:"{{cliente}}, tienes {{cantidad}} {{numero_numeros}} {{reservado_reservados}}.",
  clasificacion:"SEGURO", nota:"Reemplaza el hack \"(s)\" por concordancia real." },
{ id:"ed3e719c-b979-46e2-b5f5-349cbde811e8", tipo:"cantidad_reservas", nombre:"Súper corta", habilitada:true,
  antes:"Tienes {{cantidad}}.", propuesto:null, clasificacion:"NO_APLICA", nota:"No menciona \"número(s)\", nada que concuerde." },
{ id:"d9a9f626-8bd9-4105-b5d0-2c158108cd69", tipo:"cantidad_reservas", nombre:"WhatsApp", habilitada:true,
  antes:"{{cliente}}, llevas {{cantidad}} número(s) 📋",
  propuesto:"{{cliente}}, llevas {{cantidad}} {{numero_numeros}} 📋",
  clasificacion:"SEGURO", nota:"Reemplaza el hack \"(s)\"." },
{ id:"57f08dd6-7077-4624-91f8-544ae6225471", tipo:"cantidad_reservas", nombre:"Amigable", habilitada:true,
  antes:"¡Hola {{cliente}}! Llevas {{cantidad}} número(s) reservado(s).",
  propuesto:"¡Hola {{cliente}}! Llevas {{cantidad}} {{numero_numeros}} {{reservado_reservados}}.",
  clasificacion:"SEGURO", nota:"Reemplaza el hack \"(s)\"." },
{ id:"0ba2e158-bc92-4a10-b754-dc7c6237eb5f", tipo:"cantidad_reservas", nombre:"Entusiasta", habilitada:true,
  antes:"{{cliente}}, ¡ya tienes {{cantidad}}! Sigue así 🎉", propuesto:null, clasificacion:"NO_APLICA", nota:"Sin sustantivo que concuerde." },
{ id:"51889f0c-c431-4e21-9061-4d16be9f0e74", tipo:"cantidad_reservas", nombre:"Buena suerte", habilitada:true,
  antes:"{{cantidad}} reservados, {{cliente}}. ¡Mucha suerte! 🍀",
  propuesto:"{{cantidad}} {{reservado_reservados}}, {{cliente}}. ¡Mucha suerte! 🍀",
  clasificacion:"SEGURO", nota:"\"reservados\" es fijo y se rompe con cantidad=1 (\"1 reservados\")." },
{ id:"38468929-5f0d-480a-94c9-df19cb2ce62a", tipo:"cantidad_reservas", nombre:"Detallada", habilitada:true,
  antes:"{{cliente}}, según nuestro registro tienes actualmente {{cantidad}} número(s) reservado(s).",
  propuesto:"{{cliente}}, según nuestro registro tienes actualmente {{cantidad}} {{numero_numeros}} {{reservado_reservados}}.",
  clasificacion:"SEGURO", nota:"Reemplaza el hack \"(s)\"." },
{ id:"57bfd959-ded1-4480-ab58-5b9f17e4b464", tipo:"cantidad_reservas", nombre:"Directa", habilitada:true,
  antes:"{{cantidad}}", propuesto:null, clasificacion:"NO_APLICA", nota:"Solo el número, sin texto." },
{ id:"100c9565-024c-41c0-a6fd-bcfe8d9b382f", tipo:"cantidad_reservas", nombre:"Casual", habilitada:true,
  antes:"{{cliente}}, tienes {{cantidad}}.", propuesto:null, clasificacion:"NO_APLICA", nota:"Sin sustantivo que concuerde." },
{ id:"4081a754-5e83-4e7e-884d-9d141dce4ac2", tipo:"cantidad_reservas", nombre:"Profesional", habilitada:true,
  antes:"Estimado {{cliente}}, la cantidad de números reservados a su nombre es: {{cantidad}}.",
  propuesto:null, clasificacion:"NO_APLICA",
  nota:"\"la cantidad de números\" es un rótulo de categoría (como \"cantidad de manzanas\"): queda invariante en plural aunque el valor sea 1 (\"la cantidad de números... es: 1\" es correcto). \"es\" concuerda con \"la cantidad\" (singular), no con el conteo — falso positivo del regex." },
{ id:"daa0a5fe-707e-4533-9a77-fb4637121085", tipo:"cantidad_reservas", nombre:"Resumen", habilitada:true,
  antes:"Cantidad: {{cantidad}}", propuesto:null, clasificacion:"NO_APLICA", nota:"Etiqueta sin sustantivo." },
{ id:"8df965f0-0687-49b0-8408-34cf12bc5eeb", tipo:"cantidad_reservas", nombre:"Enfocada en evento", habilitada:true,
  antes:"{{cliente}}, para {{evento}} llevas {{cantidad}} número(s).",
  propuesto:"{{cliente}}, para {{evento}} llevas {{cantidad}} {{numero_numeros}}.",
  clasificacion:"SEGURO", nota:"Reemplaza el hack \"(s)\"." },
{ id:"32c51a5d-4f31-4421-b73b-3f48136219a3", tipo:"cantidad_reservas", nombre:"Enfocada en números", habilitada:true,
  antes:"Total de números tuyos: {{cantidad}}", propuesto:null, clasificacion:"NO_APLICA", nota:"Rótulo de UI, convención habitual mantener plural como categoría (\"Total de números tuyos: 1\" es aceptable, como \"Followers: 1\")." },
{ id:"38bdfce7-b221-487c-af8b-2e2165aaf98a", tipo:"cantidad_reservas", nombre:"Casual + emojis", habilitada:true,
  antes:"{{cliente}} 🔢 llevas {{cantidad}} números ✨",
  propuesto:"{{cliente}} 🔢 llevas {{cantidad}} {{numero_numeros}} ✨",
  clasificacion:"SEGURO", nota:"BUG REAL: \"llevas 1 números\" está mal con la plantilla actual." },
{ id:"ca5163cd-699d-46aa-a36d-e6369661d861", tipo:"cantidad_reservas", nombre:"Personalizada", habilitada:true,
  antes:"", propuesto:null, clasificacion:"NO_APLICA", nota:"Vacía." },

// ============================== disponibilidad ==============================
// cantidad = numerosDisponibles.length. numeros_ocupados es una LISTA
// INDEPENDIENTE (puede tener una cantidad distinta) — no hay variable
// central que concuerde con ESA lista todavía, así que cualquier plantilla
// que la describa gramaticalmente (no solo la liste) queda REQUIERE_REVISION.
{ id:"2806fefb-c508-4fc8-b824-64de1f21d46b", tipo:"disponibilidad", nombre:"Natural", habilitada:false,
  antes:"Números disponibles: {{numeros_disponibles}}",
  propuesto:"{{numero_numeros}} {{disponible_disponibles}}: {{numeros_disponibles}}",
  clasificacion:"SEGURO", nota:"Mismo bug que se corrigió en resolverConsulta.js (\"Números disponibles (1)\")." },
{ id:"ab1112dc-fd32-42d9-b5bb-be9cb0f3f341", tipo:"disponibilidad", nombre:"Súper corta", habilitada:false,
  antes:"Libres: {{numeros_disponibles}}", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"Libres\"/\"Libre\" no está entre las 9 variables (no existe libre_libres todavía)." },
{ id:"81575ddd-37af-4403-9253-577ae2820f49", tipo:"disponibilidad", nombre:"WhatsApp", habilitada:false,
  antes:"Quedan disponibles: {{numeros_disponibles}} 😊", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"Quedan\"/\"Queda\" (verbo quedar) no está cubierto por ninguna variable." },
{ id:"f4ec117c-3531-40ac-97d9-871b68f0f581", tipo:"disponibilidad", nombre:"Amigable", habilitada:true,
  antes:"¡Hola! \nEstos números siguen disponibles: {{numeros_disponibles}}", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"Estos\"/\"Este\" y \"siguen\"/\"sigue\" no están cubiertos; migrar solo \"disponibles\" dejaría el resto incoherente." },
{ id:"f8ce4931-2710-421d-8817-41451848db10", tipo:"disponibilidad", nombre:"Entusiasta", habilitada:true,
  antes:"¡Todavía hay buenos números! \n\nDisponibles: {{numeros_disponibles}} 🎉", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"buenos\"/\"bueno\" no está cubierto; migrar solo \"Disponibles:\" dejaría \"buenos números\" incoherente si hay 1." },
{ id:"b16141fd-e8c1-476d-83a0-554e23e2990e", tipo:"disponibilidad", nombre:"Buena suerte", habilitada:true,
  antes:"Disponibles: {{numeros_disponibles}}. ¡Elige el tuyo y mucha suerte! 🍀",
  propuesto:"{{numero_numeros}} {{disponible_disponibles}}: {{numeros_disponibles}}. ¡Elige el tuyo y mucha suerte! 🍀",
  clasificacion:"SEGURO", nota:"\"Elige el tuyo\" es invariante (imperativo genérico), no necesita cambiar." },
{ id:"c5792222-f259-4d89-87b3-aedfb3b4053c", tipo:"disponibilidad", nombre:"Detallada", habilitada:true,
  antes:"Para {{evento}}, los números que aún están disponibles son: {{numeros_disponibles}}. Los ya ocupados son: {{numeros_ocupados}}.",
  propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"La mitad de \"disponibles\" sería segura sola, pero \"Los ya ocupados son\" describe numeros_ocupados (cantidad independiente) — no hay variable central para esa cantidad todavía." },
{ id:"b5d712a6-72ba-41e0-a275-1d162e0ce57e", tipo:"disponibilidad", nombre:"Directa", habilitada:true,
  antes:"Disponibles: {{numeros_disponibles}}",
  propuesto:"{{numero_numeros}} {{disponible_disponibles}}: {{numeros_disponibles}}",
  clasificacion:"SEGURO", nota:null },
{ id:"526fcd5f-55d5-402f-a07b-3def0ebfb27e", tipo:"disponibilidad", nombre:"Casual", habilitada:true,
  antes:"Quedan: {{numeros_disponibles}}", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"Quedan\"/\"Queda\" no cubierto." },
{ id:"05fe6053-d2ef-43d7-bce9-bb2025d9206f", tipo:"disponibilidad", nombre:"Profesional", habilitada:true,
  antes:"Se informa que los números disponibles actualmente son: {{numeros_disponibles}}.",
  propuesto:"Se informa que {{el_numero_los_numeros}} {{disponible_disponibles}} actualmente {{es_son}}: {{numeros_disponibles}}.",
  clasificacion:"SEGURO", nota:"Sujeto único (números disponibles), sin preposición \"de\"/\"a\" antes de la variable — sin riesgo de contracción." },
{ id:"13370614-1447-4493-a1e6-49b05823a118", tipo:"disponibilidad", nombre:"Resumen", habilitada:true,
  antes:"Disponibles ({{numeros_disponibles}}). Ocupados ({{numeros_ocupados}}).", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"Igual que \"Detallada\": \"Ocupados (N)\" depende de una cantidad independiente (numeros_ocupados) sin variable central propia." },
{ id:"2faa2a5b-d8b1-4c0b-b151-ba84e9118be2", tipo:"disponibilidad", nombre:"Enfocada en evento", habilitada:true,
  antes:"Para {{evento}}, disponibles: {{numeros_disponibles}}",
  propuesto:"Para {{evento}}, {{disponible_disponibles}}: {{numeros_disponibles}}",
  clasificacion:"SEGURO", nota:null },
{ id:"ecec0ace-d0f4-42f2-8bea-20031098fa24", tipo:"disponibilidad", nombre:"Enfocada en números", habilitada:true,
  antes:"Números libres: {{numeros_disponibles}}", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"libres\"/\"libre\" no cubierto; \"Números\" solo no se puede migrar sin dejar \"libres\" suelto e incoherente." },
{ id:"fff00b52-6e02-47f6-be2c-b9d1b2f99800", tipo:"disponibilidad", nombre:"Casual + emojis", habilitada:true,
  antes:"¡Quedan varios! 👀 {{numeros_disponibles}} disponibles 🔥", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"Quedan\"/\"queda\" y \"varios\" (sin forma singular natural aquí) requieren reescritura manual, no un simple swap de variable." },
{ id:"6afc741e-8c64-4043-ac86-d7e11f61120b", tipo:"disponibilidad", nombre:"Personalizada", habilitada:true,
  antes:"", propuesto:null, clasificacion:"NO_APLICA", nota:"Vacía." },

// ============================== info_evento ==============================
// Nunca habla de varios números — siempre UN evento. Las coincidencias de
// "es" son el verbo copulativo de "Es {{evento}}", sin relación con conteo.
// Ninguna se migra (regla explícita del pedido: no migrar info_evento por
// simples coincidencias de "es").
{ id:"446355da-f7df-484c-bf42-a9af104e1981", tipo:"info_evento", nombre:"Natural", habilitada:true, antes:"Este sorteo es: {{evento}}, a las {{hora}}.", propuesto:null, clasificacion:"NO_APLICA", nota:"\"es\" no depende de ninguna cantidad de números." },
{ id:"00361096-5929-4ab2-b0cf-28c9e20b9872", tipo:"info_evento", nombre:"Súper corta", habilitada:true, antes:"{{evento}} — {{hora}}", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"c2e1dc61-ca36-4077-a016-29367cd67428", tipo:"info_evento", nombre:"WhatsApp", habilitada:true, antes:"Es {{evento}}, hoy a las {{hora}} 😊", propuesto:null, clasificacion:"NO_APLICA", nota:"\"es\" no depende de conteo." },
{ id:"e7dcc589-39f1-465a-932d-34a573c5483e", tipo:"info_evento", nombre:"Amigable", habilitada:true, antes:"¡Hola! El sorteo es {{evento}}, a las {{hora}}.", propuesto:null, clasificacion:"NO_APLICA", nota:"\"es\" no depende de conteo." },
{ id:"a087b0ef-b948-4863-a18b-a74b1070d379", tipo:"info_evento", nombre:"Entusiasta", habilitada:true, antes:"¡Es {{evento}}! Sorteo a las {{hora}} 🎉 ¡mucha suerte!", propuesto:null, clasificacion:"NO_APLICA", nota:"\"Es\" no depende de conteo." },
{ id:"36e6081a-46f4-4ce2-8bd3-604b0a682941", tipo:"info_evento", nombre:"Buena suerte", habilitada:true, antes:"{{evento}} a las {{hora}}. ¡Suerte para todos! 🍀", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"a1809c2e-339e-4c5c-877c-71f2e72e044f", tipo:"info_evento", nombre:"Detallada", habilitada:true, antes:"El evento activo actualmente es {{evento}}, programado para el {{fecha}} a las {{hora}}.", propuesto:null, clasificacion:"NO_APLICA", nota:"\"es\" no depende de conteo." },
{ id:"b65fb6f6-e4dd-4223-9c2b-498df1eb7479", tipo:"info_evento", nombre:"Directa", habilitada:true, antes:"{{evento}}, {{hora}}", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"24cfcc26-32be-4e78-9431-8db36b765c34", tipo:"info_evento", nombre:"Casual", habilitada:true, antes:"Es {{evento}}, {{hora}}.", propuesto:null, clasificacion:"NO_APLICA", nota:"\"Es\" no depende de conteo." },
{ id:"0c1d4ff5-514e-4fd3-8a7d-73cab2253f06", tipo:"info_evento", nombre:"Profesional", habilitada:true, antes:"Se informa que el sorteo vigente es {{evento}}, con cierre programado a las {{hora}} del {{fecha}}.", propuesto:null, clasificacion:"NO_APLICA", nota:"\"es\" no depende de conteo." },
{ id:"8c4da938-16a8-4f87-8470-5f78bedae4ff", tipo:"info_evento", nombre:"Resumen", habilitada:true, antes:"Evento: {{evento}} | Hora: {{hora}}", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"f1361171-fb24-451b-a540-a4fe2c021aa4", tipo:"info_evento", nombre:"Enfocada en evento", habilitada:true, antes:"Sorteo: {{evento}} — Fecha: {{fecha}} — Hora: {{hora}}", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"8b03c73c-e81a-4ad2-8ed8-b0af973d816e", tipo:"info_evento", nombre:"Enfocada en números", habilitada:true, antes:"Hora del sorteo {{evento}}: {{hora}}", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"b61473f1-8750-4b97-afa2-bc7d8de64024", tipo:"info_evento", nombre:"Casual + emojis", habilitada:true, antes:"¡Es {{evento}}! 🎯 a las {{hora}} ✨🍀", propuesto:null, clasificacion:"NO_APLICA", nota:"\"Es\" no depende de conteo." },
{ id:"5d39b642-5edc-48dc-9ed7-f69ac3e80396", tipo:"info_evento", nombre:"Personalizada", habilitada:true, antes:"", propuesto:null, clasificacion:"NO_APLICA", nota:"Vacía." },

// ============================== mis_numeros ==============================
// cantidad = numerosDelUsuario.length (una sola lista: numeros_reservados).
{ id:"74af4804-4202-4c63-a51f-0e910531cd1c", tipo:"mis_numeros", nombre:"Natural", habilitada:false,
  antes:"{{cliente}}, tus números son: {{numeros_reservados}}",
  propuesto:"{{cliente}}, {{tu_numero_tus_numeros}} {{es_son}}: {{numeros_reservados}}",
  clasificacion:"SEGURO", nota:null },
{ id:"3d1c9cf6-958f-45fc-a867-b7689df1c57d", tipo:"mis_numeros", nombre:"Súper corta", habilitada:false,
  antes:"Tus números: {{numeros_reservados}}",
  propuesto:"{{tu_numero_tus_numeros}}: {{numeros_reservados}}",
  clasificacion:"SEGURO", nota:"Se pierde la mayúscula inicial (cosmético); revisar antes de habilitar." },
{ id:"8cef5427-5b3d-410e-bf97-dd35e80350e8", tipo:"mis_numeros", nombre:"WhatsApp", habilitada:false,
  antes:"{{cliente}}, estos son los tuyos: {{numeros_reservados}} 😊", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"estos\"/\"este\" y \"tuyos\"/\"tuyo\" no están cubiertos." },
{ id:"c544f353-d284-45d4-aee7-01b7da65c883", tipo:"mis_numeros", nombre:"Amigable", habilitada:true,
  antes:"¡Hola! \nEstos son tus números: {{numeros_reservados}}", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"HABILITADA. \"Estos\"/\"Este\" no está cubierto (\"tus números\"/\"son\" sí lo estarían solos)." },
{ id:"db30dd23-d97d-4d30-9311-92d6328b1f2c", tipo:"mis_numeros", nombre:"Entusiasta", habilitada:false,
  antes:"{{cliente}}, ¡tienes {{numeros_reservados}}! Mucha suerte con ellos 🍀", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"ellos\"/\"él\" (pronombre) no está cubierto." },
{ id:"41ad2b7d-4cc8-4ca0-a317-4d52672e2ada", tipo:"mis_numeros", nombre:"Buena suerte", habilitada:false,
  antes:"{{numeros_reservados}} son tuyos, {{cliente}}. ¡Que ganes! 🎉", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"tuyos\"/\"tuyo\" no está cubierto (\"son\" sí lo estaría solo)." },
{ id:"f1161cfb-c28d-461e-97d5-ca234d62fd26", tipo:"mis_numeros", nombre:"Detallada", habilitada:false,
  antes:"{{cliente}}, según nuestro registro, tus números reservados son: {{numeros_reservados}}.",
  propuesto:"{{cliente}}, según nuestro registro, {{tu_numero_tus_numeros}} {{reservado_reservados}} {{es_son}}: {{numeros_reservados}}.",
  clasificacion:"SEGURO", nota:null },
{ id:"b9bbeadd-563c-4837-a69d-96597a32c0a0", tipo:"mis_numeros", nombre:"Directa", habilitada:false,
  antes:"{{numeros_reservados}}", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"9b8af65c-0908-4c40-ad22-77e823ef56ab", tipo:"mis_numeros", nombre:"Casual", habilitada:false,
  antes:"{{cliente}}, tienes: {{numeros_reservados}}", propuesto:null, clasificacion:"NO_APLICA", nota:"\"tienes\" es invariante (2a persona)." },
{ id:"f6856786-5074-46d6-98ba-161bd7175f91", tipo:"mis_numeros", nombre:"Profesional", habilitada:false,
  antes:"Estimado {{cliente}}, sus números registrados son: {{numeros_reservados}}.", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"sus\"/\"su\" (posesivo formal) y \"registrados\"/\"registrado\" no están cubiertos (no existe una variante formal de tu_numero_tus_numeros todavía)." },
{ id:"3cd06a25-2305-40f1-b6a2-440316bbfa3d", tipo:"mis_numeros", nombre:"Resumen", habilitada:false,
  antes:"Tuyos: {{numeros_reservados}}", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"Tuyos\"/\"Tuyo\" (pronombre posesivo) no está cubierto." },
{ id:"4d77c834-4c3f-48c2-b6f2-df6db59ec2bb", tipo:"mis_numeros", nombre:"Enfocada en evento", habilitada:false,
  antes:"{{cliente}}, para {{evento}} tienes: {{numeros_reservados}}", propuesto:null, clasificacion:"NO_APLICA", nota:"\"tienes\" invariante." },
{ id:"50f4f64e-f9d7-488d-b758-b22e35160db7", tipo:"mis_numeros", nombre:"Enfocada en números", habilitada:false,
  antes:"Números a tu nombre: {{numeros_reservados}}",
  propuesto:"{{numero_numeros}} a tu nombre: {{numeros_reservados}}",
  clasificacion:"SEGURO", nota:null },
{ id:"747cc431-e757-49e3-997c-6d0c3fe81b2d", tipo:"mis_numeros", nombre:"Casual + emojis", habilitada:false,
  antes:"{{cliente}} 🎫 tus números son {{numeros_reservados}} ✨",
  propuesto:"{{cliente}} 🎫 {{tu_numero_tus_numeros}} {{es_son}} {{numeros_reservados}} ✨",
  clasificacion:"SEGURO", nota:null },
{ id:"4d006f3a-2418-43c6-b4c2-76385efde5d6", tipo:"mis_numeros", nombre:"Personalizada", habilitada:false,
  antes:"", propuesto:null, clasificacion:"NO_APLICA", nota:"Vacía." },

// ============================== mis_reservas ==============================
// Misma fuente que mis_numeros (numerosDelUsuario) — una sola lista.
{ id:"0d1d9e35-fd5e-48e0-b276-4818d8671990", tipo:"mis_reservas", nombre:"Natural", habilitada:true,
  antes:"*Hola.*\n*Esto es lo que tienes reservado: {{numeros_reservados}}*", propuesto:null, clasificacion:"NO_APLICA",
  nota:"HABILITADA, pero YA es correcta para cualquier cantidad: \"esto\"/\"es\"/\"reservado\" concuerdan con el pronombre neutro \"esto\" (invariante), no con la lista de números — como en \"esto es lo que tienes reservado: 45\" o \"...: 12, 20\", ambas correctas." },
{ id:"42e710d5-ca43-4a4d-b4cb-6d2aa85044a7", tipo:"mis_reservas", nombre:"Súper corta", habilitada:false,
  antes:"Reservado: {{numeros_reservados}}",
  propuesto:"{{reservado_reservados}}: {{numeros_reservados}}",
  clasificacion:"SEGURO", nota:"Se pierde la mayúscula inicial (cosmético)." },
{ id:"c7efd335-4b0e-4d21-8be7-8e8cf695230d", tipo:"mis_reservas", nombre:"WhatsApp", habilitada:false,
  antes:"{{cliente}}, tienes reservado: {{numeros_reservados}} 📋",
  propuesto:"{{cliente}}, tienes {{reservado_reservados}}: {{numeros_reservados}} 📋",
  clasificacion:"SEGURO", nota:"\"reservado\" aquí concuerda con la lista que sigue (\"tienes reservados 12, 20\"), no es invariante como en la Natural." },
{ id:"6918b958-b51f-443c-9b2c-730d535e660f", tipo:"mis_reservas", nombre:"Amigable", habilitada:false,
  antes:"¡Hola {{cliente}}! Esto tienes reservado hasta ahora: {{numeros_reservados}}", propuesto:null, clasificacion:"NO_APLICA",
  nota:"\"Esto ... reservado\" — mismo patrón neutro invariante que \"Natural\"." },
{ id:"d06c8835-af54-45b5-81dd-d2472c141de2", tipo:"mis_reservas", nombre:"Entusiasta", habilitada:false,
  antes:"{{cliente}}, ¡tienes reservado {{numeros_reservados}}! 🎉",
  propuesto:"{{cliente}}, ¡tienes {{reservado_reservados}} {{numeros_reservados}}! 🎉",
  clasificacion:"SEGURO", nota:"Sin \"esto\" de por medio: \"reservado\" concuerda directamente con la lista." },
{ id:"b22c4793-624c-418b-9ea1-c47815e71adc", tipo:"mis_reservas", nombre:"Buena suerte", habilitada:false,
  antes:"{{numeros_reservados}} reservado a tu nombre, {{cliente}}. ¡Suerte!",
  propuesto:"{{numeros_reservados}} {{reservado_reservados}} a tu nombre, {{cliente}}. ¡Suerte!",
  clasificacion:"SEGURO", nota:null },
{ id:"c6dbcba9-4d3a-4259-9437-09f02e2bf05a", tipo:"mis_reservas", nombre:"Detallada", habilitada:false,
  antes:"{{cliente}}, en {{evento}} tienes reservado actualmente: {{numeros_reservados}}.",
  propuesto:"{{cliente}}, en {{evento}} tienes {{reservado_reservados}} actualmente: {{numeros_reservados}}.",
  clasificacion:"SEGURO", nota:null },
{ id:"244d9032-07f1-48e7-91c5-d773a09bf320", tipo:"mis_reservas", nombre:"Directa", habilitada:false,
  antes:"{{numeros_reservados}}", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"1ccaf95f-2da0-4290-a171-ec6f7bdde563", tipo:"mis_reservas", nombre:"Casual", habilitada:false,
  antes:"{{cliente}}, tienes: {{numeros_reservados}}", propuesto:null, clasificacion:"NO_APLICA", nota:"\"tienes\" invariante." },
{ id:"9925c87a-011e-4ed1-932c-7c5fdac206de", tipo:"mis_reservas", nombre:"Profesional", habilitada:false,
  antes:"Estimado {{cliente}}, su reserva actual es: {{numeros_reservados}}.", propuesto:null, clasificacion:"NO_APLICA",
  nota:"\"su reserva ... es\" — \"reserva\" es un sustantivo singular invariante (\"la reserva\" contiene 1 o varios números), no concuerda con la cantidad de números." },
{ id:"a5123bb1-6af9-4644-b80c-61f75ba744c7", tipo:"mis_reservas", nombre:"Resumen", habilitada:false,
  antes:"Reserva actual: {{numeros_reservados}}", propuesto:null, clasificacion:"NO_APLICA", nota:"\"Reserva\" singular invariante, igual que Profesional." },
{ id:"c20e084a-e18e-4933-8996-0c35c05e53ec", tipo:"mis_reservas", nombre:"Enfocada en evento", habilitada:false,
  antes:"{{cliente}}, para {{evento}} tu reserva es: {{numeros_reservados}}", propuesto:null, clasificacion:"NO_APLICA", nota:"\"tu reserva es\" invariante, igual que Profesional." },
{ id:"b18f50c5-1182-4efa-b927-65647e808448", tipo:"mis_reservas", nombre:"Enfocada en números", habilitada:false,
  antes:"Reservado a tu nombre: {{numeros_reservados}}",
  propuesto:"{{reservado_reservados}} a tu nombre: {{numeros_reservados}}",
  clasificacion:"SEGURO", nota:"Se pierde mayúscula inicial (cosmético)." },
{ id:"542e0721-2809-4084-98a0-459aea1cf852", tipo:"mis_reservas", nombre:"Casual + emojis", habilitada:false,
  antes:"{{cliente}} 📋 llevas reservado {{numeros_reservados}} ✨",
  propuesto:"{{cliente}} 📋 llevas {{reservado_reservados}} {{numeros_reservados}} ✨",
  clasificacion:"SEGURO", nota:null },
{ id:"ebd896f5-502c-4236-92f5-c48b70e68efa", tipo:"mis_reservas", nombre:"Personalizada", habilitada:false,
  antes:"", propuesto:null, clasificacion:"NO_APLICA", nota:"Vacía." },

// ============================== numero_especifico ==============================
// Siempre EXACTAMENTE 1 número (por diseño: resolverConsulta.js solo toma
// numeros[0]). Ya son singulares/neutras en las 15 — no hay nada que migrar.
{ id:"299b3383-7770-4fba-ba50-13897d1a60bd", tipo:"numero_especifico", nombre:"Natural", habilitada:false, antes:"{{cliente}}, sobre el {{numeros_solicitados}}: te cuento su estado.", propuesto:null, clasificacion:"NO_APLICA", nota:"Siempre 1 número por definición del tipo." },
{ id:"c170eda8-f7dc-4dcb-af4b-3499d6ac13c7", tipo:"numero_especifico", nombre:"Súper corta", habilitada:false, antes:"{{numeros_solicitados}}: revisado.", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"4485f72d-b9ad-446c-9575-a2c385fa4bff", tipo:"numero_especifico", nombre:"WhatsApp", habilitada:false, antes:"{{cliente}}, ya revisé el {{numeros_solicitados}} por ti 👍", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"141a2f52-4385-40ea-bb1d-70b311683ec8", tipo:"numero_especifico", nombre:"Amigable", habilitada:false, antes:"¡Hola {{cliente}}! Consultando el número {{numeros_solicitados}} para ti.", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya singular, correcto." },
{ id:"cb748048-ecdf-4825-a2af-a8adc60b5f3e", tipo:"numero_especifico", nombre:"Entusiasta", habilitada:false, antes:"{{cliente}}, ¡vamos a ver qué pasó con el {{numeros_solicitados}}! 🔎", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"32d27673-c1dd-4550-8387-3d97784660d7", tipo:"numero_especifico", nombre:"Buena suerte", habilitada:false, antes:"Revisando {{numeros_solicitados}} para ti, {{cliente}}.", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"eb25caee-cf13-413b-b67e-1aace7e9e260", tipo:"numero_especifico", nombre:"Detallada", habilitada:false, antes:"{{cliente}}, con respecto al número {{numeros_solicitados}} que consultaste para {{evento}}, este es su estado actual.", propuesto:null, clasificacion:"NO_APLICA", nota:"\"este\" ya singular, correcto." },
{ id:"b2af9095-2f65-4894-9668-5c578f11a55f", tipo:"numero_especifico", nombre:"Directa", habilitada:false, antes:"{{numeros_solicitados}}: estado consultado.", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"5a9537e1-1220-4b3c-a9b0-35d6f183897a", tipo:"numero_especifico", nombre:"Casual", habilitada:false, antes:"{{cliente}}, el {{numeros_solicitados}}:", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"0f477528-9f63-4de4-be3e-31e48a1e4911", tipo:"numero_especifico", nombre:"Profesional", habilitada:false, antes:"Estimado {{cliente}}, en relación al número {{numeros_solicitados}} consultado, le informamos su estado.", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya singular, correcto." },
{ id:"9a4bf266-0eb5-4cc5-9f83-9172e656414a", tipo:"numero_especifico", nombre:"Resumen", habilitada:false, antes:"{{numeros_solicitados}} — estado:", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"3ac28bbd-93f5-4134-9c4c-0b98f1a47df5", tipo:"numero_especifico", nombre:"Enfocada en evento", habilitada:false, antes:"{{cliente}}, en {{evento}} el número {{numeros_solicitados}} tiene este estado:", propuesto:null, clasificacion:"NO_APLICA", nota:"\"este\" ya singular." },
{ id:"dd182f5b-9cae-4426-a242-76e5b4815a0e", tipo:"numero_especifico", nombre:"Enfocada en números", habilitada:false, antes:"Número consultado: {{numeros_solicitados}}", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya singular, correcto." },
{ id:"966b6acd-1dde-413c-8c4c-d4efd250695e", tipo:"numero_especifico", nombre:"Casual + emojis", habilitada:false, antes:"{{cliente}} 🔎 el {{numeros_solicitados}}... ¡vamos a ver! ✨", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"65376b3b-0743-49f0-9d58-092a35f2a328", tipo:"numero_especifico", nombre:"Personalizada", habilitada:false, antes:"", propuesto:null, clasificacion:"NO_APLICA", nota:"Vacía." },

// ============================== numero_ocupado ==============================
// Siempre EXACTAMENTE 1 solicitado (calcularTipoPresentacion: solicitados.length===1).
// Las 15 ya están correctamente en singular — nada que migrar.
{ id:"41263ed4-e7c7-49f0-811d-7b4405902aaa", tipo:"numero_ocupado", nombre:"Natural", habilitada:true, antes:"*El número {{numeros_solicitados}} ya está ocupado. ❌*", propuesto:null, clasificacion:"NO_APLICA", nota:"Siempre 1 por definición del tipo; ya singular correcto." },
{ id:"bbfa12b2-83ba-4c89-ab45-f0ebc714fd1b", tipo:"numero_ocupado", nombre:"Súper corta", habilitada:true, antes:"*{{numeros_solicitados}} ya está ocupado. ❌*", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"85f12c8d-856a-491d-8170-e3c511c32ae5", tipo:"numero_ocupado", nombre:"WhatsApp", habilitada:false, antes:"Uy {{cliente}}, {{numeros_solicitados}} ya tiene dueño 🙏", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"81d90abc-22a7-4632-8226-4f367625c4ce", tipo:"numero_ocupado", nombre:"Amigable", habilitada:true, antes:"¡Hola! Lo sentimos.\nEl {{numeros_solicitados}} ya fue tomado por otra persona. ", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya singular correcto." },
{ id:"367941f2-014d-4ed2-9522-753ee76c2621", tipo:"numero_ocupado", nombre:"Entusiasta", habilitada:false, antes:"{{cliente}}, casi lo logras, pero {{numeros_solicitados}} ya se fue 😅 ¡anímate con otro!", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"85e0fe9c-def8-447c-9d13-a97451801dc7", tipo:"numero_ocupado", nombre:"Buena suerte", habilitada:false, antes:"{{numeros_solicitados}} ya no está libre. ¡Prueba con otro número, seguro hay suerte! 🍀", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"dfb3c7a2-7610-4079-95a4-8448ac811684", tipo:"numero_ocupado", nombre:"Detallada", habilitada:false, antes:"{{cliente}}, el número {{numeros_solicitados}} que solicitaste para {{evento}} ya se encuentra ocupado por otro participante.", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"4dc4f044-c610-4bf3-b006-c9309478d1db", tipo:"numero_ocupado", nombre:"Directa", habilitada:false, antes:"{{numeros_solicitados}}: ocupado.", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"30fcd083-5cab-4775-8ff8-a7e3f0896e5f", tipo:"numero_ocupado", nombre:"Casual", habilitada:false, antes:"{{cliente}}, ese ya no está. {{numeros_solicitados}} ocupado.", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"f9254947-f4a1-4b53-b80b-c7b31b76fc08", tipo:"numero_ocupado", nombre:"Profesional", habilitada:false, antes:"Estimado {{cliente}}, le informamos que el número {{numeros_solicitados}} ya no se encuentra disponible.", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"f05b7076-8346-4e55-b914-89bf51d762fc", tipo:"numero_ocupado", nombre:"Resumen", habilitada:false, antes:"{{numeros_solicitados}} → ocupado.", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"1cc23f25-f24c-434a-bf71-51a26fab9aee", tipo:"numero_ocupado", nombre:"Enfocada en evento", habilitada:false, antes:"{{cliente}}, en {{evento}} el número {{numeros_solicitados}} ya fue reservado por otra persona.", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"07240243-2eaf-499c-8af3-a0f81a084231", tipo:"numero_ocupado", nombre:"Enfocada en números", habilitada:false, antes:"El número {{numeros_solicitados}} ya está ocupado.", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"2b06be4e-238a-4d7b-ba69-f94fbc976ac1", tipo:"numero_ocupado", nombre:"Casual + emojis", habilitada:false, antes:"{{cliente}} 😅 el {{numeros_solicitados}} ya voló, ¡prueba con otro! 🔥", propuesto:null, clasificacion:"NO_APLICA", nota:null },
{ id:"17c5fc7c-0f75-4869-98f0-b1ec0779d122", tipo:"numero_ocupado", nombre:"Personalizada", habilitada:false, antes:"", propuesto:null, clasificacion:"NO_APLICA", nota:"Vacía." },

// ============================== todos_ocupados ==============================
// Siempre >= 2 solicitados (complemento de numero_ocupado). Ya están en
// plural correcto en 14/15 — solo "Natural" tiene un error PREEXISTENTE
// ("El números", artículo singular + sustantivo plural) que la migración
// corrige de paso.
{ id:"3770ded4-8493-4836-8423-ebc91c100b8f", tipo:"todos_ocupados", nombre:"Natural", habilitada:true,
  antes:"*El números {{numeros_solicitados}} ya están ocupados. ❌*",
  propuesto:"*{{el_numero_los_numeros}} {{numeros_solicitados}} ya {{esta_estan}} {{ocupado_ocupados}}. ❌*",
  clasificacion:"SEGURO", nota:"BONUS: corrige un error PREEXISTENTE (\"El números\" → \"Los números\"), no solo gramática de cantidad. HABILITADA." },
{ id:"c8cb9a8a-0b7b-41e4-b38e-974fc012d75c", tipo:"todos_ocupados", nombre:"Súper corta", habilitada:true, antes:"*{{numeros_solicitados}} ya ocupados. ❌*", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto (tipo siempre ≥2); sustitución opcional, no obligatoria." },
{ id:"5a361e4e-c01b-4c75-a994-5e792a9fb25e", tipo:"todos_ocupados", nombre:"WhatsApp", habilitada:false, antes:"{{cliente}}, esos ya no estaban 🙏 {{numeros_solicitados}} ocupados.", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto." },
{ id:"1afcc485-3e36-4c38-aa37-a2e7082077de", tipo:"todos_ocupados", nombre:"Amigable", habilitada:true, antes:"*¡Hola!*\n*ya fueron tomados. ❌*", propuesto:null, clasificacion:"NO_APLICA",
  nota:"Ya plural correcto. Nota aparte (no es un bug de gramática): no menciona {{numeros_solicitados}} — no dice CUÁLES números; fuera del alcance de esta migración." },
{ id:"07df342a-7f96-47da-b5b0-1dc9d699d2cd", tipo:"todos_ocupados", nombre:"Entusiasta", habilitada:false, antes:"{{cliente}}, {{numeros_solicitados}} ya volaron 😅 ¡intenta con otros!", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto." },
{ id:"9e7ab8d7-5f0c-4dd5-8314-deffa793f58c", tipo:"todos_ocupados", nombre:"Buena suerte", habilitada:false, antes:"{{numeros_solicitados}} ya no están libres. ¡Ánimo, prueba con otros números! 🍀", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto." },
{ id:"6fa60e3b-e76f-4440-b87b-c9c3a312859c", tipo:"todos_ocupados", nombre:"Detallada", habilitada:false, antes:"{{cliente}}, los números {{numeros_solicitados}} que solicitaste para {{evento}} ya se encuentran ocupados por otros participantes.", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto." },
{ id:"95f2f125-4a81-4ff4-9126-643285933688", tipo:"todos_ocupados", nombre:"Directa", habilitada:false, antes:"buenas todos ocupados.", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto (fuera de eso, redacción informal preexistente, no es un problema de gramática de cantidad)." },
{ id:"9c61ce1d-0747-44d1-a7bb-456c92297e56", tipo:"todos_ocupados", nombre:"Casual", habilitada:false, antes:"{{cliente}}, esos ya no hay. {{numeros_solicitados}} ocupados.", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto." },
{ id:"69971467-6d3d-413f-b6d6-7935602779ac", tipo:"todos_ocupados", nombre:"Profesional", habilitada:false, antes:"Estimado {{cliente}}, le informamos que los números {{numeros_solicitados}} ya no se encuentran disponibles.", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto." },
{ id:"5cf507e7-3c8f-48d3-8680-9bbf31aa7503", tipo:"todos_ocupados", nombre:"Resumen", habilitada:false, antes:"{{numeros_solicitados}} → todos ocupados.", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto." },
{ id:"acfffd31-485e-43b1-a0f7-edd111e49fcc", tipo:"todos_ocupados", nombre:"Enfocada en evento", habilitada:false, antes:"{{cliente}}, en {{evento}} los números {{numeros_solicitados}} ya fueron reservados por otras personas.", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto." },
{ id:"46e86b6f-e491-461f-b2ef-ff00faaa25cd", tipo:"todos_ocupados", nombre:"Enfocada en números", habilitada:false, antes:"Los números {{numeros_solicitados}} ya están ocupados.", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto (y con el artículo correcto)." },
{ id:"5da750d6-cbe0-4ba6-892a-3d994de43a55", tipo:"todos_ocupados", nombre:"Casual + emojis", habilitada:false, antes:"{{cliente}} 😬 {{numeros_solicitados}} ya se fueron todos, ¡prueba con otros! 🔥", propuesto:null, clasificacion:"NO_APLICA", nota:"Ya plural correcto." },
{ id:"dd4a2ddb-56a4-452f-945c-0e9000b55717", tipo:"todos_ocupados", nombre:"Personalizada", habilitada:false, antes:"", propuesto:null, clasificacion:"NO_APLICA", nota:"Vacía." },

// ============================== reserva_completa ==============================
// cantidad = numerosReservados.length (una sola lista).
{ id:"0f16f7b5-d6bc-4bb5-ac09-1947ed5a37d1", tipo:"reserva_completa", nombre:"Natural", habilitada:true,
  antes:"*¡Listo! ✅*\n*Quedaron reservados: {{numeros_reservados}} 🎟️*", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"HABILITADA. \"Quedaron\"/\"Quedó\" (verbo quedar) no está cubierto por ninguna variable; migrar solo \"reservados\" dejaría \"Quedaron reservado\" roto en singular." },
{ id:"94e7d409-0fbd-450c-b461-b7f9633828f1", tipo:"reserva_completa", nombre:"Súper corta", habilitada:false,
  antes:"Reservado: {{numeros_reservados}} ✅",
  propuesto:"{{reservado_reservados}}: {{numeros_reservados}} ✅",
  clasificacion:"SEGURO", nota:"Se pierde mayúscula inicial (cosmético)." },
{ id:"70aa34c2-3edb-4d85-af3b-a2a9fb5c50bf", tipo:"reserva_completa", nombre:"WhatsApp", habilitada:false,
  antes:"{{cliente}}, tus números {{numeros_reservados}} ya quedaron reservados 👍", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"quedaron\"/\"quedó\" no cubierto (\"tus números\"/\"reservados\" sí lo estarían solos)." },
{ id:"df654592-727b-4a3b-ac9d-829a8c871744", tipo:"reserva_completa", nombre:"Amigable", habilitada:true,
  antes:"*Con gusto reservamos {{numeros_reservados}} para ti ✅*", propuesto:null, clasificacion:"NO_APLICA",
  nota:"\"reservamos\" es 1a persona plural (\"nosotros\"), invariante — no concuerda con la cantidad de números reservados. Ya correcta." },
{ id:"0377e472-380a-4ce3-9835-0b2a48f3a7c3", tipo:"reserva_completa", nombre:"Entusiasta", habilitada:false,
  antes:"¡Genial {{cliente}}! {{numeros_reservados}} son tuyos, mucha suerte 🎉", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"\"tuyos\"/\"tuyo\" no cubierto (\"son\" sí lo estaría solo)." },
{ id:"a350a802-a8d0-44fe-9f30-c9500bb795a4", tipo:"reserva_completa", nombre:"Buena suerte", habilitada:true,
  antes:"*Numeros {{numeros_reservados}} reservados.* ✅\n*¡Que la suerte te acompañe! 🍀*",
  propuesto:"*{{numero_numeros}} {{numeros_reservados}} {{reservado_reservados}}.* ✅\n*¡Que la suerte te acompañe! 🍀*",
  clasificacion:"SEGURO", nota:"BONUS: corrige el typo \"Numeros\" (sin tilde) de paso. HABILITADA." },
{ id:"0bfa8eab-a113-4bca-a25b-2f8e6b79a2e6", tipo:"reserva_completa", nombre:"Detallada", habilitada:false,
  antes:"{{cliente}}, confirmamos la reserva de {{numeros_reservados}} para {{evento}} a las {{hora}}. Valor por número: ${{precio}}.", propuesto:null, clasificacion:"NO_APLICA",
  nota:"\"confirmamos\" (1a plural) y \"la reserva\"/\"Valor por número\" son invariantes (\"por número\" es distributivo, no concuerda con el total). Ya correcta." },
{ id:"0ef0e0f4-65d1-44dc-9a89-3a2b3f991489", tipo:"reserva_completa", nombre:"Directa", habilitada:false,
  antes:"Reservados {{numeros_reservados}}.",
  propuesto:"{{reservado_reservados}} {{numeros_reservados}}.",
  clasificacion:"SEGURO", nota:"Se pierde mayúscula inicial (cosmético)." },
{ id:"d51d7070-9011-496d-b1d4-605b368199be", tipo:"reserva_completa", nombre:"Casual", habilitada:true,
  antes:"*Listo, ya quedaron {{numeros_reservados}} a su nombre. ✅*", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"HABILITADA. \"quedaron\"/\"quedó\" no cubierto." },
{ id:"fb62d468-6cf6-48bb-8308-2c517497bcb4", tipo:"reserva_completa", nombre:"Profesional", habilitada:true,
  antes:"*Listo, confirmamos la reserva de los números {{numeros_reservados}} para {{evento}}.  ✅*\n", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"HABILITADA. \"de los números\" → singular sería \"del número\" (contracción de+el); sustituir {{el_numero_los_numeros}} tal cual produciría \"de el número\" (incorrecto). Requiere ajuste manual de la preposición, no un simple swap." },
{ id:"ac73994a-be8b-43a3-8055-ac102c2b0c05", tipo:"reserva_completa", nombre:"Resumen", habilitada:false,
  antes:"{{numeros_reservados}} reservados para {{cliente}}.",
  propuesto:"{{numeros_reservados}} {{reservado_reservados}} para {{cliente}}.",
  clasificacion:"SEGURO", nota:null },
{ id:"bcf41933-2755-47a6-93ca-d0fb6d4ea892", tipo:"reserva_completa", nombre:"Enfocada en evento", habilitada:true,
  antes:"*Tus números {{numeros_reservados}} quedaron reservados para {{evento}}. ✅*", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"HABILITADA. \"quedaron\"/\"quedó\" no cubierto (\"Tus números\"/\"reservados\" sí lo estarían solos)." },
{ id:"b496ac5b-82cd-43b7-9c5c-29d7807776d8", tipo:"reserva_completa", nombre:"Enfocada en números", habilitada:false,
  antes:"{{numeros_reservados}} → reservados a nombre de {{cliente}}.",
  propuesto:"{{numeros_reservados}} → {{reservado_reservados}} a nombre de {{cliente}}.",
  clasificacion:"SEGURO", nota:null },
{ id:"88b84d22-e6c2-468d-a249-a8e28d184268", tipo:"reserva_completa", nombre:"Casual + emojis", habilitada:true,
  antes:"*¡Perfecto! 🥳*\n*{{numeros_reservados}} son tuyos🍀✨*", propuesto:null, clasificacion:"REQUIERE_REVISION",
  nota:"HABILITADA. \"tuyos\"/\"tuyo\" no cubierto (\"son\" sí lo estaría solo)." },
{ id:"1f9d57a0-3082-4f05-a7c0-c797c98b83a2", tipo:"reserva_completa", nombre:"Personalizada", habilitada:false, antes:"", propuesto:null, clasificacion:"NO_APLICA", nota:"Vacía." },
{ id:"7b769717-4448-49d3-b67a-bb95871ff3a2", tipo:"reserva_completa", nombre:"Nueva plantilla", habilitada:false, antes:"", propuesto:null, clasificacion:"NO_APLICA", nota:"Vacía." },

// ============================== reserva_parcial ==============================
// DOS listas independientes (numeros_reservados y numeros_ocupados), cada
// una con su propia cantidad. Las 9 variables actuales solo pueden
// concordar con UNA cantidad por respuesta (cantidadPropiedad = la de
// reservados) — por eso ninguna fila de este tipo es 100% migrable sin
// riesgo: la mitad que describe "ocupados" quedaría atada a la cantidad
// equivocada. Además, casi todas usan verbos no cubiertos (quedaron,
// tenían, se adelantaron, volaron, listos, tuyos, confirmados, libres).
{ id:"349bfbd6-7128-4ec0-8aec-05a48f938f67", tipo:"reserva_parcial", nombre:"Natural", habilitada:true, antes:"*{{numeros_reservados}} quedaron reservados. ✅*\n\n*{{numeros_ocupados}} ya estaban ocupados. ❌*", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"HABILITADA. \"quedaron\" no cubierto + \"ocupados\" en la cláusula de numeros_ocupados dependería de una cantidad distinta a la de numeros_reservados." },
{ id:"5e1cc8c0-503e-470f-9785-fd56ff9045d9", tipo:"reserva_parcial", nombre:"Súper corta", habilitada:false, antes:"Reservados: {{numeros_reservados}}. Ocupados: {{numeros_ocupados}}.", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"Reservados:\" sería seguro migrar solo, pero \"Ocupados:\" depende de una cantidad independiente sin variable central propia todavía." },
{ id:"94e8dcae-3bcd-47c7-93a8-45473853a98c", tipo:"reserva_parcial", nombre:"WhatsApp", habilitada:false, antes:"{{cliente}}, logramos apartar {{numeros_reservados}}. {{numeros_ocupados}} ya no estaban disponibles 🙏", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"estaban disponibles\" describe numeros_ocupados — cantidad independiente, riesgo de concordancia cruzada." },
{ id:"8eb3f83a-5397-4aba-82d7-7c241b42a980", tipo:"reserva_parcial", nombre:"Amigable", habilitada:true, antes:"*¡Hola!*\n*Te reservamos {{numeros_reservados}}. ✅*\n\n*Lo sentimos, {{numeros_ocupados}} ya tenían dueño. ❌*", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"HABILITADA. \"tenían\"/\"tenía\" no cubierto, y describe la lista de ocupados (cantidad independiente)." },
{ id:"7779a315-d5eb-4418-ba5e-3c1f607142ac", tipo:"reserva_parcial", nombre:"Entusiasta", habilitada:false, antes:"{{cliente}}, ¡{{numeros_reservados}} son tuyos! {{numeros_ocupados}} se adelantaron 😅", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"tuyos\" no cubierto; \"se adelantaron\"/\"se adelantó\" tampoco (describe ocupados, cantidad independiente)." },
{ id:"95682c37-2610-4c81-926d-1b567ee9e74b", tipo:"reserva_parcial", nombre:"Buena suerte", habilitada:false, antes:"{{numeros_reservados}} reservados para ti, {{cliente}}. ¡Suerte con esos números! ({{numeros_ocupados}} ya estaban tomados)", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"tomados\"/\"tomado\" no cubierto; \"estaban\" describe ocupados (cantidad independiente)." },
{ id:"7a97f45e-0283-47da-bdf6-37d4294f946a", tipo:"reserva_parcial", nombre:"Detallada", habilitada:false, antes:"{{cliente}}, para {{evento}}: se reservaron {{numeros_reservados}} a tu nombre; {{numeros_ocupados}} ya estaban ocupados por otra persona.", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"se reservaron\"/\"se reservó\" no cubierto; \"estaban ocupados\" describe ocupados (cantidad independiente)." },
{ id:"d3b90e01-4716-4169-bd57-4a3cef51ea88", tipo:"reserva_parcial", nombre:"Directa", habilitada:false, antes:"Reservados: {{numeros_reservados}}. No disponibles: {{numeros_ocupados}}.", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"No disponibles:\" describe ocupados — cantidad independiente sin variable central propia." },
{ id:"a54d9281-22f7-4ed1-8a9d-9bcee5921f38", tipo:"reserva_parcial", nombre:"Casual", habilitada:false, antes:"{{cliente}}, {{numeros_reservados}} listos. {{numeros_ocupados}} ya no había.", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"listos\"/\"listo\" no cubierto." },
{ id:"fcfcf3f0-72cc-47fe-94fa-c5c13fec44d7", tipo:"reserva_parcial", nombre:"Profesional", habilitada:false, antes:"Estimado {{cliente}}, se confirma la reserva parcial: {{numeros_reservados}}. Los números {{numeros_ocupados}} no estaban disponibles.", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"Los números ... no estaban disponibles\" describe ocupados — cantidad independiente." },
{ id:"321203cf-a91d-4f16-94e6-a3958a2895b2", tipo:"reserva_parcial", nombre:"Resumen", habilitada:false, antes:"{{numeros_reservados}} reservados / {{numeros_ocupados}} ocupados.", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"ocupados\" describe numeros_ocupados — cantidad independiente de \"reservados\"." },
{ id:"ed82b548-bb17-47d8-9322-389649e10e68", tipo:"reserva_parcial", nombre:"Enfocada en evento", habilitada:false, antes:"{{cliente}}, en {{evento}} quedaron reservados {{numeros_reservados}}; {{numeros_ocupados}} ya no estaban libres.", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"quedaron\" y \"libres\" no cubiertos." },
{ id:"f59f8116-b47b-4509-aa3a-77c272f43f3e", tipo:"reserva_parcial", nombre:"Enfocada en números", habilitada:false, antes:"Solicitaste varios números: {{numeros_reservados}} confirmados, {{numeros_ocupados}} ya ocupados.", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"varios\" y \"confirmados\"/\"confirmado\" no cubiertos; \"ocupados\" describe lista independiente." },
{ id:"017ac38c-be46-491a-8e6e-7eede6170cb4", tipo:"reserva_parcial", nombre:"Casual + emojis", habilitada:false, antes:"{{cliente}} 🙌 {{numeros_reservados}} son tuyos, pero {{numeros_ocupados}} ya volaron 😬🔥", propuesto:null, clasificacion:"REQUIERE_REVISION", nota:"\"tuyos\" no cubierto; \"volaron\"/\"voló\" tampoco (describe ocupados)." },
{ id:"f7fdee96-7df4-4cad-b151-62172a73e56b", tipo:"reserva_parcial", nombre:"Personalizada", habilitada:false, antes:"", propuesto:null, clasificacion:"NO_APLICA", nota:"Vacía." }

];
